Vagrant.configure("2") do |config|

  config.vm.define "vicgarciS" do |s|
    s.vm.box = "generic/alpine318"
    s.vm.hostname = "vicgarciS"
    s.vm.network "private_network", ip: "192.168.56.110"

    s.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end                                

	s.vm.synced_folder ".", "/vagrant"

	s.vm.provision "shell", inline: 
	<<-SHELL
	curl -sfL https://get.k3s.io | sh -s - --node-ip=192.168.56.110
	for i in $(seq 1 30); do
		if [ -f /var/lib/rancher/k3s/server/node-token ]; then
    		break
		fi
		sleep 2
	done
	until sudo k3s kubectl get nodes --no-headers | grep -q 'Ready'; do
    	echo "Waiting for k3s server to be ready..."
		sleep 2
	done
	echo "Waiting for k3s node to be Ready..."

	while true; do
   		STATUS=$(kubectl get node "$(hostname)" -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
	    if [ "$STATUS" == "True" ]; then
			echo "✅ Node is Ready!"
        	break
    	else
        	echo "⏳ Node not ready yet. Current status: $STATUS"
        	sleep 2
		fi
	done

	echo "---SERVER TOKEN---"
	cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
	SHELL
  end

  config.vm.define "vicgarciSW" do |sw|
    sw.vm.box = "generic/alpine318"
	sw.vm.hostname = "vicgarciSW"
    sw.vm.network "private_network", ip: "192.168.56.111"

    sw.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

	sw.vm.synced_folder ".", "/vagrant"

	sw.vm.provision "shell", inline: 
	<<-SHELL
	echo "---READING_TOKEN---"
	TOKEN=$(cat /vagrant/node-token)
	curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN="$TOKEN" sh -s - --node-ip=192.168.56.111
	SHELL
  end

end
